# Generated by Django 4.1 on 2022-10-17 06:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('rua', models.CharField(max_length=50, verbose_name='rua')),
                ('numero', models.CharField(max_length=50, verbose_name='numero')),
                ('cep', models.CharField(max_length=50, verbose_name='cep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status_pedido', models.CharField(blank='Ad', choices=[('Ad', 'Andamento'), ('EV', 'enviado'), ('Fi', 'Finalizado'), ('En', 'Entregue'), ('Cn', 'Cancelado')], max_length=2, null='Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo_do_produto', models.IntegerField(verbose_name='Codigo de produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='fotos/%Y/%m/', variations={}, verbose_name='foto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False, unique=True, verbose_name='Telefone')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='path/to/img', variations={}, verbose_name='foto')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('password', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_Car')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='core.cliente')),
                ('produtos', models.ManyToManyField(blank=True, to='core.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
