# Generated by Django 4.1 on 2022-11-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produto_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='produto_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo_do_produto', models.IntegerField(verbose_name='Codigo de produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='estoque')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/%Y/%m/', variations={}, verbose_name='foto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='telefone')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='path/to/img', variations={}, verbose_name='foto')),
                ('comentario', models.TextField(null=True, verbose_name='Comentario')),
                ('rua', models.CharField(max_length=50, null=True, verbose_name='rua')),
                ('numero', models.CharField(max_length=50, null=True, verbose_name='numero')),
                ('cep', models.CharField(max_length=50, null=True, verbose_name='cep')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status_pedido', models.CharField(blank=True, choices=[('Ad', 'Andamento'), ('EV', 'enviado'), ('Fi', 'Finalizado'), ('En', 'Entregue'), ('Cn', 'Cancelado')], max_length=2, null=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='produto',
            field=models.ManyToManyField(blank=True, to='core.produto'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
