# Generated by Django 4.1.1 on 2022-10-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='foto',
            field=models.ImageField(blank=True, upload_to='path/to/img', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/', verbose_name='foto'),
        ),
    ]
