# Generated by Django 4.1 on 2022-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_car_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
