# Generated by Django 4.1 on 2022-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Total'),
        ),
    ]
