# Generated by Django 4.1 on 2022-10-09 21:07

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='path/to/img', variations={}, verbose_name='foto'),
        ),
    ]
