# Generated by Django 4.1 on 2022-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_car_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
